# Generated by Django 5.2.4 on 2025-08-10 13:31

import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sporthistories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excersice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ns', 'not start'), ('w', 'working'), ('f', 'finished')], default='ns', max_length=2)),
                ('sport_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excersices', to='sporthistories.sporthistory')),
            ],
        ),
        migrations.CreateModel(
            name='Excersice_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('time', models.DateField()),
                ('excersice_time', models.DurationField()),
                ('description', models.TextField()),
                ('excersice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excersice_history', to='excersices.excersice')),
            ],
        ),
        migrations.AddConstraint(
            model_name='excersice',
            constraint=models.UniqueConstraint(fields=('sport_history', 'name'), name='unique_excersice'),
        ),
    ]
