# Generated by Django 5.2.4 on 2025-08-14 11:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysessions', '0002_mysession_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysession',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='mysession',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3), blank=True, default=list, size=None),
        ),
    ]
