# Generated by Django 5.2.4 on 2025-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysessions', '0003_remove_mysession_days_of_week_mysession_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysession',
            name='name',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
    ]
