# Generated by Django 5.2.4 on 2025-08-06 05:59

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_created_at'),
        ('users', '0009_alter_miduser_balance_rial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9),
        ),
        migrations.CreateModel(
            name='RecpetionistPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=0, max_digits=9)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specific_payments', to='users.receptionist')),
            ],
        ),
    ]
