# Generated by Django 5.2.4 on 2025-08-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_amount_recpetionistpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recpetionistpayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
