# Generated by Django 5.2.4 on 2025-08-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicusers', '0001_initial'),
        ('memberships', '0001_initial'),
        ('plans', '0001_initial'),
        ('reservations', '0001_initial'),
        ('sporthistories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'failed')], default='pending', max_length=7)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('registered_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='basicusers.miduser')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=9)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='plans.nutritionplan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=9)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='memberships.membership')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='orders.order')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='reservations.reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SportHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='orders.order')),
                ('sporthistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sporthistories.sporthistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
