# Generated by Django 5.2.4 on 2025-08-22 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_membership_status_activation_alter_membership_status'),
        ('orders', '0004_membershipitem_public_id_nutritionplanitem_public_id_and_more'),
        ('plans', '0008_alter_nutritionplan_status'),
        ('reservations', '0005_alter_reservation_reserved_by'),
        ('sporthistories', '0008_alter_sporthistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipitem',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='memberships.membership'),
        ),
        migrations.AlterField(
            model_name='nutritionplanitem',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='plans.nutritionplan'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='sporthistoryitem',
            name='sporthistory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sporthistories.sporthistory'),
        ),
    ]
