# Generated by Django 5.2.4 on 2025-08-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('basicusers', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_rial', models.DecimalField(decimal_places=0, max_digits=9)),
                ('status', models.CharField(choices=[('ack', 'accepted'), ('nack', 'not accepted'), ('wait', 'waiting_list')], default='wait', max_length=4)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('registered_date', models.DateField(null=True)),
                ('athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserves', to='athletes.athlete')),
                ('class_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserves', to='classes.class')),
                ('reserved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve_requests', to='basicusers.miduser')),
            ],
        ),
    ]
