# Generated by Django 5.2.4 on 2025-08-17 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_class_class_salary_get_per_athlete_rial_and_more'),
        ('reservations', '0003_reservation_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='class_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='classes.class'),
        ),
    ]
