# Generated by Django 5.2.4 on 2025-08-05 12:01

import django.contrib.auth.models
import django.db.models.deletion
import users.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('miduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.miduser')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.miduser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('miduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.miduser')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.miduser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='miduser',
            old_name='address',
            new_name='home_address',
        ),
        migrations.AddField(
            model_name='miduser',
            name='balance_rial',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='balance'),
        ),
        migrations.AddField(
            model_name='miduser',
            name='status',
            field=models.CharField(choices=[('ac', 'active'), ('inac', 'inactive'), ('ex', 'expired')], default='ac', max_length=4),
        ),
        migrations.AlterField(
            model_name='miduser',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='miduser',
            name='home_number',
            field=models.CharField(max_length=11, validators=[users.helpers.validate_iran_home_phone]),
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('miduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.miduser')),
                ('wieght', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('classes', models.ManyToManyField(blank=True, related_name='athletes', to='training.class')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.miduser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recived_messages', to='users.miduser')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_messages', to='users.miduser')),
            ],
        ),
        migrations.CreateModel(
            name='SportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('confirmation_coach', models.BooleanField(default=False)),
                ('balance_for_coaching_rial', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='balance for coaching(rial)')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_historys', to='users.athlete')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_coaching', to='users.coach')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='coachs',
            field=models.ManyToManyField(blank=True, related_name='athletes', through='users.SportHistory', to='users.coach'),
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('activity_description', models.TextField(blank=True, null=True, verbose_name='activity description(not required)')),
                ('start_activity', models.DateField()),
                ('end_activity', models.DateField()),
                ('lastest_salary_rial', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='lastes salary(rial)')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='users.miduser')),
            ],
        ),
    ]
