# Generated by Django 5.2.4 on 2025-08-05 12:13

import users.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_miduser_home_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miduser',
            name='home_number',
            field=models.CharField(max_length=11, validators=[users.helpers.validate_iran_home_phone]),
        ),
    ]
