# Generated by Django 5.2.4 on 2025-08-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_miduser_home_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('receptionist', 'Receptionist'), ('coach', 'Coach'), ('manager', 'Manager'), ('athlete', 'Athelete'), ('none', 'None'), ('admin', 'Admin')], default='none', max_length=20),
        ),
    ]
