# Generated by Django 5.2.4 on 2025-08-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_baseuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('receptionist', 'Receptionist'), ('coach', 'Coach'), ('manager', 'Manager'), ('athlete', 'Athelete'), ('admin', 'Admin')], default='athlete', max_length=20),
        ),
    ]
