# Generated by Django 5.2.4 on 2025-08-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('users', '0006_alter_baseuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='managers', to='reports.report'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='wieght',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
