# Generated by Django 5.2.4 on 2025-08-06 02:32

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_manager_reports_alter_athlete_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sporthistory',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporthistory',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='end_activity',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='start_activity',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
