# Generated by Django 5.2.4 on 2025-08-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_message_created_at_alter_message_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miduser',
            name='balance_rial',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='sporthistory',
            name='balance_for_coaching_rial',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='balance for coaching(rial)'),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='lastest_salary_rial',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='lastes salary(rial)'),
        ),
    ]
