# Generated by Django 5.2.4 on 2025-08-06 06:18

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_miduser_balance_rial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='date_login',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
    ]
