# Generated by Django 5.2.4 on 2025-08-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_baseuser_date_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='date_login',
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sporthistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporthistory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='end_activity',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='start_activity',
            field=models.DateField(),
        ),
    ]
