# Generated by Django 5.2.4 on 2025-08-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_salary', models.DecimalField(decimal_places=0, max_digits=18)),
                ('ouput_salary', models.DecimalField(decimal_places=0, max_digits=18)),
            ],
        ),
    ]
