# Generated by Django 5.2.4 on 2025-08-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysessions', '0003_remove_mysession_days_of_week_mysession_days'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassPricingItem',
            new_name='ClassItemPricing',
        ),
    ]
