# Generated by Django 5.2.4 on 2025-08-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_rename_classpricingitem_classitempricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classpricing',
            name='end_start_date',
        ),
        migrations.RemoveField(
            model_name='classpricing',
            name='gym_fee',
        ),
        migrations.RemoveField(
            model_name='classpricing',
            name='start_start_date',
        ),
    ]
