# Generated by Django 5.2.4 on 2025-08-15 12:16

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_remove_classpricing_end_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classitempricing',
            name='public_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
