# Generated by Django 5.2.4 on 2025-08-15 17:45

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_classitempricing_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershippricing',
            old_name='type',
            new_name='type_name',
        ),
        migrations.AddField(
            model_name='sporthistorypricing',
            name='end_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporthistorypricing',
            name='gym_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sporthistorypricing',
            name='start_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
