# Generated by Django 5.2.4 on 2025-08-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_rename_type_membershippricing_type_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classitempricing',
            old_name='seesion_ref',
            new_name='session_ref',
        ),
    ]
