# Generated by Django 5.2.4 on 2025-08-09 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('activity_description', models.TextField(blank=True, null=True, verbose_name='activity description(not required)')),
                ('start_activity', models.DateField()),
                ('end_activity', models.DateField()),
                ('lastest_salary_rial', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='lastes salary(rial)')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='basicusers.miduser')),
            ],
        ),
    ]
