# Generated by Django 5.2.4 on 2025-08-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0002_mymessage_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymessage',
            name='read_status',
            field=models.CharField(choices=[('r', 'read'), ('n', 'not read')], default='n', max_length=1),
        ),
    ]
