# Generated by Django 5.2.4 on 2025-08-20 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0003_mymessage_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymessage',
            name='read_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
