# Generated by Django 5.2.4 on 2025-08-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0004_mymessage_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='read_at',
            field=models.DateField(null=True),
        ),
    ]
