# Generated by Django 5.2.4 on 2025-08-20 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0005_alter_mymessage_read_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='read_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mymessage',
            name='reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recived_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mymessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
