# Generated by Django 5.2.4 on 2025-08-20 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0006_alter_mymessage_read_at_alter_mymessage_reciver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mymessage',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='mymessage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mymessage',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymessage',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymessage',
            name='read_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mymessage',
            name='read_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='mymessage',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mymessage',
            name='updated_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
