# Generated by Django 5.2.4 on 2025-08-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('users', '0002_coach_manager_receptionist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excersice',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excersices', to='users.athlete'),
        ),
        migrations.AddField(
            model_name='excersice',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excersices', to='users.coach'),
        ),
        migrations.AddField(
            model_name='excersice_history',
            name='excersice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excersice_history', to='plans.excersice'),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionplans', to='users.athlete'),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutritionplan', to='users.coach'),
        ),
        migrations.AddField(
            model_name='meal',
            name='nutrition_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to='plans.nutritionplan'),
        ),
        migrations.AddConstraint(
            model_name='excersice',
            constraint=models.UniqueConstraint(fields=('athlete', 'name'), name='unique_excersice'),
        ),
    ]
