# Generated by Django 5.2.4 on 2025-08-06 02:32

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='content',
            new_name='meal_discription',
        ),
        migrations.AddField(
            model_name='meal',
            name='athlete_date_done',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='athlete_discription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='athlete_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='excersice',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excersice',
            name='start_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='excersice_history',
            name='time',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='nutrition_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='plans.nutritionplan'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='end_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='start_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
