# Generated by Django 5.2.4 on 2025-08-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_rename_content_meal_meal_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='salary_rial',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
