# Generated by Django 5.2.4 on 2025-08-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_nutritionplan_salary_rial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excersice',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excersice',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='excersice_history',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='athlete_date_done',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
