# Generated by Django 5.2.4 on 2025-08-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('confirmation_coach', models.BooleanField(default=False)),
                ('balance_for_coaching_rial', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='balance for coaching(rial)')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_histories', to='athletes.athlete')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_histories', to='coaches.coach')),
            ],
        ),
    ]
