# Generated by Django 5.2.4 on 2025-08-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        ('sporthistories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporthistory',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_history', to='coaches.coach'),
        ),
    ]
