# Generated by Django 5.2.4 on 2025-08-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporthistories', '0002_sporthistory_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporthistory',
            name='status',
            field=models.CharField(choices=[('ns', 'not start'), ('s', 'start'), ('c', 'cancel')], default='ns', max_length=2),
        ),
    ]
