# Generated by Django 5.2.4 on 2025-08-13 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporthistories', '0003_sporthistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporthistory',
            name='balance_for_coaching_rial',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='balance for coaching(rial)'),
        ),
        migrations.AlterField(
            model_name='sporthistory',
            name='status',
            field=models.CharField(choices=[('ns', 'not start'), ('s', 'start')], default='ns', max_length=2),
        ),
    ]
