# Generated by Django 5.2.4 on 2025-08-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporthistories', '0004_alter_sporthistory_balance_for_coaching_rial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporthistory',
            name='status',
            field=models.CharField(choices=[('ns', 'not start'), ('s', 'start'), ('c', 'cancel')], default='ns', max_length=2),
        ),
    ]
