# Generated by Django 5.2.4 on 2025-08-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('sporthistories', '0005_alter_sporthistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporthistory',
            name='pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sporthistories', to='pricing.sporthistorypricing'),
        ),
    ]
