# Generated by Django 5.2.4 on 2025-08-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sporthistories', '0006_sporthistory_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporthistory',
            name='pricing',
        ),
    ]
