# Generated by Django 5.2.4 on 2025-08-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporthistories', '0007_remove_sporthistory_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporthistory',
            name='status',
            field=models.CharField(choices=[('ns', 'not start'), ('s', 'start'), ('c', 'cancel'), ('f', 'finished')], default='ns', max_length=2),
        ),
    ]
