# Generated by Django 5.2.4 on 2025-08-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporthistories', '0008_alter_sporthistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporthistory',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
