# Generated by Django 5.2.4 on 2025-08-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporthistories', '0009_alter_sporthistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporthistory',
            name='status',
            field=models.CharField(choices=[('r', 'registered'), ('nr', 'not registered'), ('c', 'cancel')], max_length=2),
        ),
    ]
