# Generated by Django 5.2.4 on 2025-08-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miduser',
            name='balance_rial',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, verbose_name='balance(rial)'),
        ),
    ]
