# Generated by Django 5.2.4 on 2025-08-18 11:33

import apps.basicusers.helpers
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicusers', '0002_alter_miduser_balance_rial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miduser',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='miduser',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='father name'),
        ),
        migrations.AlterField(
            model_name='miduser',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miduser',
            name='home_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.basicusers.helpers.validate_iran_home_phone]),
        ),
        migrations.AlterField(
            model_name='miduser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IR'),
        ),
    ]
