# Generated by Django 5.2.4 on 2025-08-09 13:10

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicusers', '0002_baseuser_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='public_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True, unique=True),
        ),
    ]
