# Generated by Django 5.2.4 on 2025-08-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('year', 'Year'), ('month', 'Month')], max_length=7)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('membership_cost_rial', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='membership cost(rial)')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='users.miduser')),
            ],
        ),
    ]
