# Generated by Django 5.2.4 on 2025-08-06 02:32

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
