# Generated by Django 5.2.4 on 2025-08-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membership_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_cost_rial',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='membership cost(rial)'),
        ),
    ]
