# Generated by Django 5.2.4 on 2025-08-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicusers', '0001_initial'),
        ('orders', '0001_initial'),
        ('receptionists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=9)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'failed')], default='pending', max_length=10)),
                ('tracking_code', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='basicusers.miduser')),
            ],
        ),
        migrations.CreateModel(
            name='RecpetionistPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=0, max_digits=9)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specific_payments', to='receptionists.receptionist')),
            ],
        ),
    ]
