# Generated by Django 5.2.4 on 2025-08-23 04:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_withdrawalrequest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recpetionistpayment',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='recpetionistpayment',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recpetionistpayment',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recpetionistpayment',
            name='updated_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='created_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
