# Generated by Django 5.2.4 on 2025-08-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_date_recpetionistpayment_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='paid_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='paid_time',
            field=models.TimeField(null=True),
        ),
    ]
