# Generated by Django 5.2.4 on 2025-08-23 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicusers', '0003_alter_miduser_age_alter_miduser_father_name_and_more'),
        ('payments', '0006_withdrawalrequest_paid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawalrequests', to='basicusers.miduser'),
        ),
    ]
