# Generated by Django 5.2.4 on 2025-08-13 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_cost_rial',
            field=models.DecimalField(decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='membership cost(rial)'),
        ),
    ]
