# Generated by Django 5.2.4 on 2025-08-13 20:26

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membership_membership_cost_rial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='public_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
