# Generated by Django 5.2.4 on 2025-08-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membership_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('year', 'Year'), ('month', 'Month')], max_length=5),
        ),
    ]
