# Generated by Django 5.2.4 on 2025-08-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_alter_membership_membership_cost_rial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='type',
            new_name='type_name',
        ),
    ]
