# Generated by Django 5.2.4 on 2025-08-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_rename_type_membership_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='status_activation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('ns', 'not start'), ('s', 'start'), ('f', 'finished')], default='ns', max_length=2),
        ),
    ]
