# Generated by Django 5.2.4 on 2025-08-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('year', 'YEAR'), ('month', 'Month'), ('year', 'Year')], max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_sale', models.DecimalField(decimal_places=0, max_digits=21)),
                ('total_payment', models.DecimalField(decimal_places=0, max_digits=15)),
                ('total_reserve', models.PositiveIntegerField()),
                ('active_user', models.PositiveIntegerField()),
                ('inactive_user', models.PositiveIntegerField()),
                ('expired_user', models.PositiveIntegerField()),
            ],
        ),
    ]
