# Generated by Django 5.2.4 on 2025-08-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_date_report_end_date_report_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
