# Generated by Django 5.2.4 on 2025-08-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
