# Generated by Django 5.2.4 on 2025-08-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_end_date_alter_report_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('year', 'YEAR'), ('month', 'Month'), ('day', 'day')], max_length=5),
        ),
    ]
