# Generated by Django 5.2.4 on 2025-08-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('year', 'YEAR'), ('month', 'Month'), ('day', 'Day')], max_length=5),
        ),
    ]
