# Generated by Django 5.2.4 on 2025-08-06 02:32

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True),
        ),
    ]
