# Generated by Django 5.2.4 on 2025-08-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_report_end_date_alter_report_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='total_sale',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
