# Generated by Django 5.2.4 on 2025-08-06 14:53

import django.core.validators
import reports.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_report_total_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(reports.helpers.find_first_user_date_joined)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateField(blank=True, validators=[django.core.validators.MinValueValidator(reports.helpers.find_first_user_date_joined)]),
        ),
    ]
