# Generated by Django 5.2.4 on 2025-08-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_report_end_date_alter_report_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='type',
            new_name='type_name',
        ),
    ]
