# Generated by Django 5.2.4 on 2025-08-07 02:12

import reports.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_rename_type_report_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateField(validators=[reports.helpers.date_validator]),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateField(blank=True, validators=[reports.helpers.date_validator]),
        ),
    ]
