# Generated by Django 5.2.4 on 2025-08-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_at', models.DateTimeField(null=True)),
                ('salary_rial', models.DecimalField(decimal_places=0, max_digits=9)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionplans', to='athletes.athlete')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_plans', to='coaches.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'wednesday'), ('thursday', 'Thursday'), ('firday', 'Friday')], max_length=10)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('meal_discription', models.TextField()),
                ('athlete_done', models.BooleanField(default=False)),
                ('athlete_date_done', models.DateField(blank=True, null=True)),
                ('athlete_discription', models.TextField()),
                ('nutrition_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='plans.nutritionplan')),
            ],
        ),
    ]
