# Generated by Django 5.2.4 on 2025-08-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('sporthistories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='excersice',
            name='unique_excersice',
        ),
        migrations.RemoveField(
            model_name='excersice',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='excersice',
            name='coach',
        ),
        migrations.AddField(
            model_name='excersice',
            name='sport_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excersices', to='sporthistories.sporthistory'),
        ),
        migrations.AddConstraint(
            model_name='excersice',
            constraint=models.UniqueConstraint(fields=('sport_history', 'name'), name='unique_excersice'),
        ),
    ]
