# Generated by Django 5.2.4 on 2025-08-10 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_excersice_unique_excersice_and_more'),
        ('sporthistories', '0002_alter_sporthistory_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excersice',
            name='sport_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excersices', to='sporthistories.sporthistory'),
        ),
    ]
