# Generated by Django 5.2.4 on 2025-08-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_nutritionplan_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='confirmation_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='status',
            field=models.CharField(choices=[('r', 'registered'), ('nr', 'not registered'), ('c', 'cancel')], default='nr', max_length=2),
        ),
    ]
