# Generated by Django 5.2.4 on 2025-08-19 13:17

import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_nutritionplan_confirmation_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='public_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='status',
            field=models.CharField(choices=[('r', 'registered'), ('nr', 'not registered'), ('c', 'cancel'), ('f', 'finished')], default='nr', max_length=2),
        ),
    ]
