# Generated by Django 5.2.4 on 2025-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_meal_public_id_alter_nutritionplan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='athlete_done',
        ),
        migrations.AlterField(
            model_name='meal',
            name='athlete_date_done',
            field=models.DateField(auto_now_add=True),
        ),
    ]
