# Generated by Django 5.2.4 on 2025-08-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_remove_meal_athlete_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='athlete_discription',
        ),
    ]
