# Generated by Django 5.2.4 on 2025-08-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_remove_meal_athlete_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='status',
            field=models.CharField(choices=[('r', 'registered'), ('nr', 'not registered'), ('f', 'finished')], default='nr', max_length=2),
        ),
    ]
