# Generated by Django 5.2.4 on 2025-08-09 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0001_initial'),
        ('mysessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('class_salary_get_per_athlete_rial', models.DecimalField(decimal_places=0, max_digits=9)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='coaches.coach')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='mysessions.mysession')),
            ],
        ),
    ]
