# Generated by Django 5.2.4 on 2025-08-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_days_remove_class_session_class_session'),
        ('pricing', '0004_classitempricing_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classses', to='pricing.classitempricing'),
        ),
    ]
