# Generated by Django 5.2.4 on 2025-08-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_class_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='pricing',
        ),
    ]
