# Generated by Django 5.2.4 on 2025-08-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_class_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('ia', 'Inactive'), ('c', 'Cancel')], default='ia', max_length=2),
        ),
    ]
