# Generated by Django 5.2.4 on 2025-08-17 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_class_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_salary_get_per_athlete_rial',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('ia', 'Inactive')], default='ia', max_length=2),
        ),
    ]
