# Generated by Django 5.2.4 on 2025-08-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_class_class_salary_get_per_athlete_rial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('ia', 'Inactive'), ('f', 'Finished')], default='ia', max_length=2),
        ),
    ]
