# Generated by Django 5.2.4 on 2025-08-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_class_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='count_registered',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
