# Generated by Django 5.2.4 on 2025-08-19 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_class_count_registered'),
        ('mysessions', '0004_mysession_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='session',
        ),
        migrations.AddField(
            model_name='class',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='mysessions.mysession'),
        ),
    ]
