# Generated by Django 5.2.4 on 2025-08-10 13:31

import apps.djalalidates.helpers
import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_name', models.CharField(choices=[('year', 'YEAR'), ('month', 'Month'), ('day', 'Day')], max_length=5)),
                ('start_date', models.DateField(blank=True, validators=[apps.djalalidates.helpers.date_validator])),
                ('end_date', models.DateField(validators=[apps.djalalidates.helpers.date_validator])),
                ('total_sale', models.DecimalField(decimal_places=0, max_digits=15)),
                ('total_payment', models.DecimalField(decimal_places=0, max_digits=15)),
                ('total_reserve', models.PositiveIntegerField()),
                ('active_user', models.PositiveIntegerField()),
                ('inactive_user', models.PositiveIntegerField()),
                ('expired_user', models.PositiveIntegerField()),
                ('public_id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='managers.manager')),
            ],
        ),
    ]
