# Generated by Django 5.2.4 on 2025-08-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type_name',
            field=models.CharField(choices=[('year', 'Year'), ('month', 'Month'), ('day', 'Day')], max_length=5),
        ),
    ]
