# Generated by Django 5.2.4 on 2025-08-13 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='total_payment',
            field=models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_sale',
            field=models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
