# Generated by Django 5.2.4 on 2025-08-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('coaches', '0001_initial'),
        ('sporthistories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='coachs',
            field=models.ManyToManyField(blank=True, related_name='athletes', through='sporthistories.SportHistory', to='coaches.coach'),
        ),
    ]
