# Generated by Django 5.2.4 on 2025-08-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('training', '0001_initial'),
        ('users', '0002_coach_manager_receptionist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='training.reservation'),
        ),
        migrations.AddField(
            model_name='sporthistoryitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='sporthistoryitem',
            name='sporthistory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.sporthistory'),
        ),
    ]
