# Generated by Django 5.2.4 on 2025-08-06 05:59

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='nutritionplanitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sporthistoryitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9),
        ),
    ]
