# Generated by Django 5.2.4 on 2025-08-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('salary_to_gym_per_athlete_rail', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('class_salary_get_per_athlete_rial', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_rial', models.DecimalField(decimal_places=0, max_digits=15)),
                ('status', models.CharField(choices=[('ack', 'accepted'), ('nack', 'not accepted'), ('wait', 'waiting_list')], default='wait', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.CharField(choices=[('even', 'Even'), ('odd', 'Odd'), ('all', 'All')], max_length=4)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
