# Generated by Django 5.2.4 on 2025-08-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        ('users', '0002_coach_manager_receptionist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='users.coach'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserves', to='users.athlete'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='class_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserves', to='training.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='training.session'),
        ),
    ]
