# Generated by Django 5.2.4 on 2025-08-06 02:34

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_reservation_date_alter_class_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='registered_date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
