# Generated by Django 5.2.4 on 2025-08-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_reservation_registered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='salary_to_gym_per_athlete_rail',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_salary_get_per_athlete_rial',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='salary_rial',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
