# Generated by Django 5.2.4 on 2025-08-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_remove_class_salary_to_gym_per_athlete_rail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='registered_date',
            field=models.DateField(null=True),
        ),
    ]
